// The /users endpoints must return what they returned before the storage moved
// under them (#313).
//
// The client calls a handful of /users/* endpoints and the split was supposed to
// be invisible to all of them. The parity that mattered during the rollout was
// flag-off vs flag-on; the flag is gone, so what is held here instead is the
// stronger version of the same property: each route's response is diffed against
// the ORIGINAL `users` query it replaced, written out verbatim. The seeded
// `users` documents are still there to diff against, and a widening that the
// old flag-off-vs-flag-on comparison could not see — how five call sites
// regressed while every check stayed green — is visible from this side.

const express = require('express');
const request = require('supertest');
const { useMongo } = require('./helpers/mongo');
const User = require('../models/user');
const SportSeason = require('../models/sportSeason');
const activeSeason = require('../modules/active-season');
const migration = require('../modules/account-migration');
const usersRouter = require('../routes/users');
const franchiseRepo = require('../modules/franchise-repo');

const app = express();
app.use(express.json());
app.use('/users', usersRouter);

useMongo();

beforeEach(async () => {
    jest.spyOn(console, 'log').mockImplementation(() => {});
    jest.spyOn(console, 'error').mockImplementation(() => {});
    activeSeason._reset();
    await SportSeason.create({ sport: 'football', season: 2026, status: 'in-season' });
    await activeSeason.prime();
});

afterEach(() => {
    jest.restoreAllMocks();
});

async function seedLeague() {
    await User.create([
        {
            firstName: 'Garrett', lastName: 'Graham', email: 'g@example.com',
            league: 'graham-league', color: '#ED5858', authSub: 'google-oauth2|123',
            avatarUrl: 'https://example.com/a.jpg', profilePrompted: true,
            isUpdated: true, lastUpdated: '9/7/2026, 11:42:28 PM',
            pushSubscriptions: [{ endpoint: 'https://push/x', keys: { p256dh: 'k', auth: 'a' } }],
            seasons: [
                { season: 2025, cumulativeScore: 163, franchiseName: 'Acuff Me Up' },
                { season: 2026, cumulativeScore: 34, franchiseName: 'Name, Image, & Sadness',
                  weeklyScore: [{ week: 1, score: 8, season: 'regular', scoreByTeam: [{ teamId: 251, gameId: 1, score: 8 }] }],
                  captains: [{ week: 1, teamId: 251 }] }
            ]
        },
        {
            firstName: 'Brock', lastName: 'McCord', email: 'b@example.com',
            league: 'graham-league', color: '#71D28D',
            seasons: [{ season: 2025, cumulativeScore: 247 }, { season: 2026, cumulativeScore: 41 }]
        },
        {
            firstName: 'Jeff', lastName: 'Claunts', email: 'j@example.com',
            league: 'claunts-league', color: '#64B5F6',
            seasons: [{ season: 2026, cumulativeScore: 12 }]
        }
    ]);
    await migration.migrate({ apply: true });
}

// Subdocument ids are regenerated by the copy and are referenced nowhere.
const strip = (v) => JSON.parse(JSON.stringify(v, (k, val) => (k === '_id' || k === '__v' ? undefined : val)));

describe('every listing endpoint still answers', () => {
    test.each([
        ['GET /users/season/:year', '/users/season/2026'],
        ['GET /users/league/:code', '/users/league/graham-league'],
        ['GET /users/league/:code (other league)', '/users/league/claunts-league'],
        ['GET /users/league/:code?season= (past season)', '/users/league/graham-league?season=2025'],
        ['GET /users (every manager)', '/users'],
        ['GET /users/league/:code/all (membership, any season)', '/users/league/graham-league/all']
    ])('%s', async (_label, path) => {
        await seedLeague();
        const res = await request(app).get(path);

        expect(res.status).toBe(200);
        // Guard against a trivially empty pass.
        expect(res.body.length).toBeGreaterThan(0);
    });

    test('an empty result is empty, not an error', async () => {
        await seedLeague();
        const res = await request(app).get('/users/league/graham-league?season=2019');
        expect(res.status).toBe(200);
        expect(res.body).toEqual([]);
    });
});

describe('what the responses must and must not contain', () => {
    test('one season only — callers index seasons[0]', async () => {
        // public/season-of.js reads the projected entry positionally, so a full
        // seasons array would quietly serve the wrong year.
        await seedLeague();
        const res = await request(app).get('/users/league/graham-league');
        res.body.forEach(u => expect(u.seasons).toHaveLength(1));
        expect(res.body[0].seasons[0].season).toBe(2026);
    });

    test('?season= projects the PAST season, not the active one', async () => {
        await seedLeague();
        const res = await request(app).get('/users/league/graham-league?season=2025');
        expect(res.body.find(u => u.firstName === 'Garrett').seasons[0]).toMatchObject({
            season: 2025, franchiseName: 'Acuff Me Up'
        });
    });

    test('the unprojected listings expose what they always exposed — parity, not an improvement', async () => {
        // GET /users and /league/:code/all ran User.find() with NO projection,
        // so they returned whole documents including authSub. Narrowing them
        // here would be a behaviour change smuggled inside a storage change; if
        // the old response carried a field, the new one has to as well. The
        // over-exposure is real and worth fixing where it reads as a fix.
        await seedLeague();
        const res = await request(app).get('/users/league/graham-league/all');
        const stored = await User.findOne({ firstName: 'Garrett' }).lean();
        const served = res.body.find(u => u.firstName === 'Garrett');
        expect(stored.authSub).toBe('google-oauth2|123');
        expect(served.authSub).toBe(stored.authSub);
    });

    test.each(['authSub', 'pushSubscriptions', 'pushPrefs'])(
        'no %s reaches the browser', async (field) => {
            await seedLeague();
            const res = await request(app).get('/users/league/graham-league');
            res.body.forEach(u => expect(u[field]).toBeUndefined());
        }
    );

    test('scores and rosters survive the swap intact', async () => {
        await seedLeague();
        const res = await request(app).get('/users/season/2026');
        const garrett = res.body.find(u => u.firstName === 'Garrett');
        expect(garrett.seasons[0].weeklyScore[0].scoreByTeam[0]).toMatchObject({ teamId: 251, score: 8 });
    });
});

// Compare a route's CURRENT response against the query it replaced, written out
// verbatim against the seeded `users` documents.
async function originalVsRoute(path, originalQuery) {
    const original = await originalQuery();
    const res = await request(app).get(path);
    return { original, body: res.body };
}

describe('responses match the query they replaced', () => {
    test('GET /users/:id/season exposes no credentials', async () => {
        // It spread an unprojected document, and /users has no per-id ownership
        // check — so any signed-in manager could read anyone else's Auth0
        // subject and their devices' push encryption keys by id.
        await seedLeague();
        const garrett = await User.findOne({ firstName: 'Garrett' }).lean();
        const { original, body } = await originalVsRoute(
            `/users/${garrett._id}/season`,
            () => User.find({ _id: garrett._id, 'seasons.season': { $eq: 2026 } },
                { firstName: 1, lastName: 1, league: 1, lastUpdated: 1, color: 1,
                  seasons: { $elemMatch: { season: { $eq: 2026 } } } }).lean()
        );
        expect(Object.keys(body[0]).sort()).toEqual(Object.keys(original[0]).sort());
        expect(body[0].authSub).toBeUndefined();
        expect(body[0].pushSubscriptions).toBeUndefined();
    });

    test('GET /users/me/push does not pull the roster subtree', async () => {
        // The route's own comment: an unprojected read "would pull ~100KB to
        // decide one boolean". Asking for `seasons` instead of `seasons.season`
        // did exactly that — 110 bytes to 107KB.
        await seedLeague();
        const garrett = await User.findOne({ firstName: 'Garrett' }).lean();
        const got = await franchiseRepo.byAccountId(garrett._id,
            { fields: ['pushSubscriptions', 'pushPrefs', 'seasons.season'] });
        expect(got.seasons.every(sn => sn.teams === undefined)).toBe(true);
        expect(got.seasons.every(sn => sn.weeklyScore === undefined)).toBe(true);
    });

    test('the admin roster keeps its projection', async () => {
        await seedLeague();
        const rows = await franchiseRepo.byLeague('graham-league', { fields: [
            'firstName', 'lastName', 'color', 'email', 'authSub',
            'seasons.season', 'seasons.teams.id', 'seasons.weeklyScore.scoreByTeam'
        ] });
        // Selected BY NAME, not by position. Asserting on rows[0] made this
        // both flaky and vacuous: Mongo's natural order varies between runs,
        // and the other manager has no franchiseName, so half the time it
        // asserted that an absent field was absent and proved nothing.
        const got = rows.find(u => u.firstName === 'Garrett');
        expect(got).toBeDefined();
        expect(got.seasons.length).toBeGreaterThan(0);

        // authSub is wanted here — it becomes `linked` on the admin panel —
        // but the heavy parts of a season must not ride along.
        expect(got.authSub).toBe('google-oauth2|123');
        got.seasons.forEach(sn => {
            expect(sn.franchiseName).toBeUndefined();
            expect(sn.captains).toBeUndefined();
        });
    });
});

describe('the reads that are not plain lists', () => {
    test('GET /users/:id returns an ARRAY, as User.find() did', async () => {
        // The client indexes [0]. Returning the bare object would break every
        // caller silently rather than loudly.
        await seedLeague();
        const garrett = await User.findOne({ firstName: 'Garrett' }).lean();
        const res = await request(app).get(`/users/${garrett._id}`);
        expect(Array.isArray(res.body)).toBe(true);
        expect(strip(res.body[0])).toMatchObject({ firstName: 'Garrett', league: 'graham-league' });
    });

    test('GET /users/:id carries the FULL seasons array, not one season', async () => {
        await seedLeague();
        const garrett = await User.findOne({ firstName: 'Garrett' }).lean();
        const res = await request(app).get(`/users/${garrett._id}`);
        expect(res.body[0].seasons.map(sn => sn.season).sort()).toEqual([2025, 2026]);
    });

    test('a membership listing spans seasons, unlike the season-scoped one', async () => {
        // /league/:code/all has no season filter — a manager who only played a
        // past season still belongs to the league.
        await seedLeague();
        const res = await request(app).get('/users/league/graham-league/all');
        expect(res.body.length).toBe(2);
        expect(res.body.map(u => u.firstName).sort()).toEqual(['Brock', 'Garrett']);
    });

    test('an unknown id is an empty array, not an error', async () => {
        await seedLeague();
        const mongoose = require('mongoose');
        const res = await request(app).get(`/users/${new mongoose.Types.ObjectId()}`);
        expect(res.status).toBe(200);
        expect(res.body).toEqual([]);
    });
});
